### ISSUE TITLE
API Docs and DB Diagram

### ISSUE THREAD

**Issue by irelius** [JosephRBryant/o2bnb#1]
# General 

We want to move the Kanban from the project itself, and have these as items on the project. We will cover more about how to do this this week, so you can skip adding this back in for now. Just remove it from the project.

 - [x] Remove Kanban Readme

# DB Diagram

The dbdiagram looks good. 

- [x] Change the names of the tables so that they're properly capitalized.

# API Docs

API endpoints also look great. Approved!

## Tasks:
- [x] Create API Docs
- [x] Add relevant API end points, following RESTFUL convention
- [x] Add proper HTTP Methods
- [x] Add Related DB Diagram to mark down

# Deadline
Please aim to complete the listed tasks by EOD on Monday, May 13th as we are looking to have all documentations approved in order to move on to the next phase of our project life cycle the following day.
